[build]
  command = "npm run build"
  functions = "api/"

[dev]
  command = "npm start"
  publish = "public/"

[[redirects]]
  from = "/api/*"
  to = "api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
